// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var bank;
    bank = {
      makeTransaction: function() {
        var balanceDiv, self, startingBalance, total, updateThePage, userInput, userInputField;
        self = $(this);
        balanceDiv = self.siblings("div.balance");
        startingBalance = parseFloat(balanceDiv.text().replace("$", ""));
        userInputField = self.siblings("input.userInput");
        userInput = parseFloat(userInputField.val());
        if (self.hasClass("deposit")) {
          total = startingBalance + (userInput || 0);
        } else {
          if (startingBalance >= userInput) {
            total = startingBalance - (userInput || 0);
          } else {
            total = startingBalance;
          }
        }
        updateThePage = function() {
          balanceDiv.html("<h2>$" + total.toFixed(2) + "</h2>");
          if ((self.hasClass("withdrawal")) && (userInput > startingBalance)) {
            balanceDiv.append("<p>Insufficient Funds!</p>");
          }
          return userInputField.val("");
        };
        return updateThePage();
      }
    };
    return $("[type=button]").on("click", bank.makeTransaction);
  });

}).call(this);
